# Generated by Django 5.0.1 on 2026-02-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for cards', max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('cattle', 'Cattle'), ('crops', 'Crops'), ('farm_overview', 'Farm Overview'), ('team', 'Team'), ('events', 'Events'), ('other', 'Other')], default='other', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet_name', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('newspaper', 'Newspaper'), ('tv', 'TV'), ('online', 'Online'), ('radio', 'Radio')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('article_url', models.URLField(blank=True, help_text='Link to the article/coverage')),
                ('description', models.TextField(blank=True)),
                ('coverage_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Media Appearance',
                'verbose_name_plural': 'Media Appearances',
                'ordering': ['-is_featured', 'order', '-coverage_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('acreage', models.DecimalField(decimal_places=2, help_text='Total acreage', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planning', 'Planning'), ('completed', 'Completed')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/hero/')),
                ('overview_image', models.ImageField(blank=True, null=True, upload_to='projects/overview/')),
                ('crops', models.CharField(blank=True, help_text='Comma-separated list of crops', max_length=500)),
                ('livestock', models.CharField(blank=True, help_text='Comma-separated list of livestock', max_length=500)),
                ('total_shares', models.IntegerField(default=0, help_text='Total number of shares available')),
                ('share_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lease_years', models.IntegerField(blank=True, help_text='Lease duration in years', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('expert', 'Expert'), ('manager', 'Manager'), ('veterinarian', 'Veterinarian'), ('other', 'Other')], max_length=50)),
                ('role_display', models.CharField(blank=True, help_text='Custom role title', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-is_featured', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('total_shares', models.IntegerField(help_text='Total shares available')),
                ('available_shares', models.IntegerField(default=0, help_text='Shares currently available')),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_return', models.CharField(blank=True, help_text='Expected ROI description', max_length=200)),
                ('investment_duration', models.CharField(blank=True, help_text='Duration of investment', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('terms_document', models.FileField(blank=True, null=True, upload_to='investment/documents/')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_opportunities', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Investment Opportunity',
                'verbose_name_plural': 'Investment Opportunities',
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
    ]
